baseURL = 'https://www.samir.fyi'
languageCode = 'en-us'
title = "Samir's blog"
theme = 'hugo-blog-awesome'


[module]
  [[hugoVersion]]
    extended = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Samir's blog"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Welcome to my blog!"

[params.author]
  avatar = "me.jpg"
  intro = "Samir Hasanov"
  name = "Samir Hasanov"
  description = "Welcome to my blog!"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

